### ISSUE TITLE
License

### ISSUE THREAD

**Issue by snoop2head** [JaeSeoKim/jaeseokim.github.io#8]
안녕하세요, 블로그를 보면서 리액트를 공부하고 있는 학생입니다.
저는 gatsby-starter-bee를 현재 사용하고 있습니다. 
https://yonsei.exchange 의 웹사이트 컨텐츠를 김재서님의 템플릿에다가 담아도 될까요? 
감사합니다.

**Comment by JaeSeoKim** [comment]
네 가능합니다!
아직 완성형이 아니여서 코드가 더럽고 오류가 나는 부분이 있을수 있을꺼에요 ㅠㅠㅠ
밑에 조그만 하게 저의 레포주소를 하나 달아주시면 감사하겠습니다!

**Comment by JaeSeoKim** [comment]
추후에 starter로 만들게 된다면 그때 다시 한번 이 이슈에서 알려드릴께요!

**Comment by snoop2head** [comment]
네 감사합니다 :)
